### ISSUE TITLE
Unexpected end of file from server

### ISSUE THREAD

**Issue by vinodss33** [pandzel/RobotsTxt#6]
Hi, I'm trying to use the library but it throws "Unexpected end of file from server" while reading and the program halts.
I was wondering if you can provide some default timeout or flexibility to timeout, that would be helpful for use for varied nature of websites.

**Comment by pandzel** [comment]
Could you provide an example of the URL causing an issue?

**Comment by vinodss33** [comment]
`15:44:34.164 [pool-1-thread-17] DEBUG c.a.e.s.ContactUsPageScrapper - Ending Thread 57 for Website http://mgeducation.org
15:46:26.557 [pool-1-thread-9] DEBUG c.a.e.scrapper.WebPageScapper - For url http://ramarajainstitute.org  Unexpected end of file from server
15:46:26.557 [pool-1-thread-8] DEBUG c.a.e.scrapper.WebPageScapper - For url http://swethaengg.org  Unexpected end of file from server
15:46:26.575 [pool-1-thread-9] DEBUG c.a.e.s.ContactUsPageScrapper - Ending Thread 18 for Website http://ramarajainstitute.org
15:46:26.596 [pool-1-thread-4] DEBUG c.a.e.scrapper.WebPageScapper - For url http://vikas.org  Unexpected end of file from server
15:46:26.623 [pool-1-thread-3] DEBUG c.a.e.scrapper.WebPageScapper - For url http://sves.co.in  Unexpected end of file from server
15:46:26.623 [pool-1-thread-3] DEBUG c.a.e.s.ContactUsPageScrapper - Ending Thread 12 for Website http://sves.co.in`

The above logs are generated in my application. I have larger number of websites so in that situation program is getting halt. So I was thinking if we can set some timeout if the server doesn't respond within the time limit, we can take appropriate action

**Comment by pandzel** [comment]
The short answer is: no, I can't do it.

The long answer is: RobotsTextReader takes a stream as a source of data and that stream is an abstract external to the 'robots' package. Any timeout handling must be implemented outside robots otherwise it would be just a poor design. You have two choices:

- read robots.txt file into the String buffer then use ByteArrayInputStream as an adapter and pass it to robots reader.
- use Apache HTTP client or something like that, set timeouts there, provide response stream to robots reader.
