### ISSUE TITLE
bots.getDisallowList(user_agent) return a list of zero length

### ISSUE THREAD

**Issue by Anda77** [pandzel/RobotsTxt#7]
Hello,

I have a issue with https://empirefilm.ro/robots.txt because the bots.getDisallowList(user_agent) return a list of zero length and I don't know why.

For other URL's bots.getDisallowList(user_agent) returns a list of one element.

Can you help me?

Thanks

**Comment by Anda77** [comment]
and user_agent = "*"

**Comment by pandzel** [comment]
I can only presume that you did open a stream to robots.txt using URL.openStream() or similar? The problem is that apparently implementation of the URL class doesn't handle HTTP protocol; it's just a simple tool to declare URL. So, if you have some redirects in between for example, then this method will not work.

Better idea is to use a better suited component like Apache HTTP client from commons library. Try adding the following dependency to your project:

    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpclient</artifactId>
      <version>4.5.4</version>
    </dependency>

then execute the following code:

    try (
            CloseableHttpClient client = HttpClients.createSystem(); 
            CloseableHttpResponse response = client.execute(new HttpGet("https://empirefilm.ro/robots.txt")); 
            InputStream robotsTxtStream = response.getEntity().getContent()
            ) {
      
      RobotsTxt robotsTxt = RobotsTxt.read(robotsTxtStream);
      List<String> disallowList = robotsTxt.getDisallowList("*");
      System.out.println(disallowList);
    }

**Comment by Anda77** [comment]
Your code works well for another URL's.
I don't know what it is the issue because I don't got any exception.

**Comment by Anda77** [comment]
I put 4 files in https://github.com/Anda77/PrjJava.

The four files are: ParseRobots_2, VerificareSEO, SEOReport and SEOReporrContentSpeed.java.

I used java 8 to run the files.

Can you help me to say why your code don't working for this URLs?

Thanks again

**Comment by pandzel** [comment]
Please, understand that 'Robots' module doesn't care about URLs at all. All it needs is a valid stream of data. Your code is feeding Robots with invalid data. Here is why:

All three URL's you are testing (https://cofetarulistet.ro/robots.txt, etc.) represents secure connections. You can tell that because they are all starting with "https" protocol at the beginning of the URL. In order to read such a stream using URL() class, each such endpoint has to present a valid SSL certificate. However, neither of these endpoint offers such a certificate (they are either invalid or expired), that's why Java refuses to do anything with that data simply because it appears as an insecure connection. 

In order to get it working your way (i.e. through URL() class) you can either talk to the owners of these urls to update certificates. If these certificates would be so called 'self-signed' certificates, you could import it into Java trusted store, but they appear to be just plain invalid.

Whenever I try to use Apache HTTP client, it seems to work correctly, which would suggest that that client can bypass ssl restrictions.

I hope it helps.

**Comment by Anda77** [comment]
How can verify that these certificate is expired or invalid?

**Comment by Anda77** [comment]
Oki, thanks for your hints and your explanation.

**Comment by pandzel** [comment]
Validating certificate could be as easy as pasting https://www.damila.ro/robots.txt into your browser. This works only if you didn't attempt it before, otherwise you might have that certificate known for the browser and stored within it's safe certification store. There is always something like lock type icon beside of the address bar (if url is https) and you can explore that certificate from there.

**Comment by Anda77** [comment]
Sorry that I insist but your code works for https://www.damila.ro/robots.txt.

I verified on https://www.sslshopper.com the 3 web site and all of them have SSL valid certificate.

But another is the reason.

I don't want to bother.

**Comment by pandzel** [comment]
There is one more thing I noticed: in case https://cofetarulistet.ro/robots.txt the returned content is not a content of the robots.txt but an html snipped with the information about redirect. URL() won't handle that.
